---
services:
  gateway:
    build:
      context: services/gateway
      dockerfile: ../../docker/service.Dockerfile
    command: uv run uvicorn gateway.main:app --host 0.0.0.0 --port 8000
    environment:
      - UVICORN_RELOAD=${UVICORN_RELOAD:-false}
    ports:
      - "8000:8000"

    develop:
      watch:
        - action: sync
          path: ./services/gateway
          target: /app
          ignore:
            - .venv
        - action: rebuild
          path: ./pyproject.toml
  
  orders:
    build:
      context: services/orders
      dockerfile: ../../docker/service.Dockerfile
    command: uv run uvicorn orders.main:app --host 0.0.0.0 --port 8000
    environment:
      - UVICORN_RELOAD=${UVICORN_RELOAD:-false}
    ports:
      - "8001:8000"

    develop:
      watch:
        - action: sync
          path: ./services/orders
          target: /app
          ignore:
            - .venv
        - action: rebuild
          path: ./pyproject.toml

  payments:
    build:
      context: services/payments
      dockerfile: ../../docker/service.Dockerfile
    command: uv run uvicorn payments.main:app --host 0.0.0.0 --port 8000
    environment:
      - UVICORN_RELOAD=${UVICORN_RELOAD:-false}
    ports:
      - "8002:8000"
    develop:
      watch:
        - action: sync
          path: ./services/payments
          target: /app
          ignore:
            - .venv
        - action: rebuild
          path: ./pyproject.toml
