[project]
name = "gateway"
version = "0.1.0"
description = "A FastAPI service for routing requests to other services"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "uvicorn>=0.34.3",
]

